### ISSUE TITLE
Add support for a dashboard view

### ISSUE THREAD

**Issue by seanmthomas** [MITLibraries/scoap3hub#101]
TopicHub currently support pages for 'administrative' functions, searches and item views, but doesn't have a single page to aggregate many of the activities that users are interested in on an ongoing basis.  A dashboard page might include:
 - a consolidated list of items pending review
 - an activity monitor that could note:
   -- a repository deposit history
   -- a TopicHub harvest history
   -- a queue of 'approved' packages awaiting deposit
 - system error logs for harvesting and/or deposit errors

**Comment by JPrevost** [comment]
I was hoping to have this ready to go already, but since it isn't quite ready I thought I'd add a screenshot of the current status:
![screen shot 2015-03-20 at 4 48 56 pm](https://cloud.githubusercontent.com/assets/1386650/6760630/1b552b06-cf21-11e4-8f5f-e27b3abbef7b.png)

**Comment by richardrodgers** [comment]
Looks fabulous out of the gate. I'm not going to have time for a detailed review of function and L&F until I return, but a few very quick observations:

* It's good to note the last harvest, but that's almost an 'implementation detail' of how content got onto the hub. For a subscriber, I would think that what he cares about is how recent the content is, how much there now is in toto, and maybe even how much has been added since he last visited the site (which presupposes we record site visit data) All this is queryable off item data directly, so we don't know/care that a harvest put it there.
E.g.

3,400 items, from 01/01/15 to 3/25/15, 700 since your last visit
(or cool visualizations of this kind of data)

The advantage of ignoring the harvest data is that we can actually get up to the second info (as each item gets added in the harvest), rather than worrying about counting an async process

* In Destinations, we should add a badge with the total delivery count (which is maintained in the channel model)

Thanks so much for this work - it really begins to synthesize a lot of user-relevant data

**Comment by JPrevost** [comment]
I agree to both, although since we don't track the Subscriber's visits yet, I'll defer that feature until after our User/Subcriber/role work this Sprint (I'll open a ticket for it though so we remember to get back this this).

I'll add the badge for the Destinations before I PR, but I also opened #132 as the counter is not currently incrementing (at least for release holds). I'm also refactoring that insane query :)
