### ISSUE TITLE
As a User, when I sign in I want to end up someplace useful

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#181]
(probably the Subscriber Dashboard... but maybe not? Not all users have a Subscriber Dashboard and some Users will have Multiple Subscriber Dashboards)

**Comment by JPrevost** [comment]
This seems reasonable I think:

- If I have one Subscriber associated with my account, I want to go to the Subscriber Dashboard.

- If I have more than one Subscriber associated with my account, I want to choose which Subscriber to be associated with for the Session and then be taken to that Subscriber Dashboard.

- If I have no Subscriber associated, I want to see a screen explaining what a Subscriber is and be given the option to create one or join and existing Subscriber.

- If I'm an Analyst or Sysadmin with no no Subscriber associated, I want to go to the Workbench.

**Comment by richardrodgers** [comment]
Seems reasonable to me also - but a few points to consider: in bullet 3, it is not clear that one should be able to elect to join (as opposed to being invited by an admin) - maybe say 'request to join existing'. In bullet 4, there may be some win in jumping to the workbench, but not as much as subscriber to dashboard. Finally, (bullet 2) I wonder whether is may be preferable to use a 'last binding' rule rather than force to choose on each login. That assumes, of course that there is a screen (user dashboard?) where one could go and change the subsciber....

**Comment by JPrevost** [comment]
:+1: to all of those comments. I've updated bullet 3 to better read "request to join" rather than "join".

I think I'd propose we handle the last binding separately as it introduces complexity on a feature that'll not get heavily used in our initial use cases (i.e. a single user with multiple subscribers is still largely a bonus feature for our initial primary use case).

**Comment by richardrodgers** [comment]
Agreed on handling last binding as a separate issue - you are right that in the initial use-cases, it is somewhat moot
